
services:

  localstack:
    container_name: localstack
    image: localstack/localstack:3.2
    ports:
      - 4563-4599:4563-4599
      - 8055:8080
    environment:
      - SERVICES=dynamodb,kms
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PERSISTENCE=1
      - DYNAMODB_SHARE_DB=1
    volumes:
      - ./storage-service/create-aws-data.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  neo4j:
    container_name: neo4j
    image: neo4j:5.16-community-bullseye
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data/

  api-gateway:
    platform: linux/x86_64
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    develop:
      watch:
        - action: rebuild
          path: ./api-gateway/pom.xml
        - action: sync
          path: ./api-gateway/src
          target: /app/src


  auth-service:
    platform: linux/x86_64
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    environment:
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      NEO4J_URI: bolt://neo4j:7687
    depends_on:
      - neo4j
    develop:
      watch:
        - action: rebuild
          path: ./auth-service/pom.xml
        - action: sync
          path: ./auth-service/src
          target: /app/src

  storage-service:
    platform: linux/x86_64
    container_name: storage-service
    build:
      context: storage-service
      dockerfile: Dockerfile
      target: base
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    environment:
      AWS_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: DUMMY
      AWS_SECRET_ACCESS_KEY: DUMMY
    depends_on:
      localstack:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./storage-service/pom.xml
        - action: sync+restart
          path: ./storage-service/src
          target: /app/src

  main-service:
    container_name: main-service
    build:
      no_cache: true
      context: main-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: npm run watch
    develop:
      watch:
        - action: rebuild
          path: ./main-service/package.json
        - action: sync
          path: ./main-service/src
          target: /app/src

    environment:
      NEO4J_PASSWORD: password
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      AUTH_SERVICE_URL: http://auth-service:8050
      STORAGE_SERVICE_URL: http://storage-service:8080
      JWT_WEB_TOKEN: supersecret_dont_share
    depends_on:
      neo4j:
        condition: service_started

  front-end:
    container_name: front-end
    build:
      no_cache: true
      context: traverse-ui
      dockerfile: Dockerfile
      target: build
      args:
        VITE_APP_BACKEND_URL: http://127.0.0.1:8081
    ports:
      - 3000:3000
    environment:
      VITE_APP_BACKEND_URL: http://127.0.0.1:8081
    command: npm start
    develop:
      watch:
        - action: rebuild
          path: ./traverse-ui/package.json
        - action: sync
          path: ./traverse-ui/src
          target: /app/src
    depends_on:
      - main-service

volumes:
  localstack_data:
  neo4j_data:
