
services:

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    depends_on:
      neo4j:
        condition: service_started

  neo4j:
    container_name: neo4j
    image: neo4j:5.16-community-bullseye
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data/

  storage-service:
    container_name: storage-service
    build:
      context: storage-service
      dockerfile: Dockerfile
      target: base
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    environment:
      MONGO_URL: mongodb://mongodb/mongodb_data
    depends_on:
      - mongodb
    develop:
      watch:
        - action: rebuild
          path: ./storage-service/pom.xml
        - action: sync+restart
          path: ./storage-service/src
          target: /app/src

  main-service:
    container_name: main-service
    build:
      no_cache: true
      context: main-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: npm run watch
    develop:
      watch:
        - action: rebuild
          path: ./main-service/package.json
        - action: sync
          path: ./main-service/src
          target: /app/src

    environment:
      NEO4J_PASSWORD: password
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      STORAGE_SERVICE_URL: http://storage-service:8080
      JWT_WEB_TOKEN: supersecret_dont_share
    depends_on:
      - neo4j

  front-end:
    container_name: front-end
    build:
      no_cache: true
      context: traverse-ui
      dockerfile: Dockerfile
      target: build
      args:
        VITE_APP_BACKEND_URL: http://127.0.0.1:8000/
        VITE_APP_STORAGE_SERVICE_URL: http://127.0.0.1:8080
    ports:
      - 3000:3000
    environment:
      VITE_APP_BACKEND_URL: http://127.0.0.1:8000/
      VITE_APP_STORAGE_SERVICE_URL: http://127.0.0.1:8080
    command: npm start
    develop:
      watch:
        - action: rebuild
          path: ./traverse-ui/package.json
        - action: sync
          path: ./traverse-ui/src
          target: /app/src
    depends_on:
      - main-service


volumes:
  mongodb_data:
  neo4j_data:
